### ISSUE TITLE
下不了依赖

### ISSUE THREAD

**Issue by qiang518** [xuexiangjys/XTask#3]
Failed to resolve: com.github.xuexiangjys:XTask:xtask-core
Show in Project Structure dialog
Affected Modules: app

**Comment by xuexiangjys** [comment]
https://github.com/xuexiangjys/XTask#%E6%B7%BB%E5%8A%A0gradle%E4%BE%9D%E8%B5%96

**Comment by wc1217** [comment]
晕死了，作者README写错了，正确的依赖应该是：` implementation 'com.github.xuexiangjys.XTask:xtask-core:1.0.2'`，XTask前面应该是一个`.`不是`:`

**Comment by xuexiangjys** [comment]
> 晕死了，作者README写错了，正确的依赖应该是：` implementation 'com.github.xuexiangjys.XTask:xtask-core:1.0.2'`，XTask前面应该是一个`.`不是`:`

已修改,谢谢提醒
